//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colligo.O365Product.RM.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADGAgent
    {
        public long ADGAgentId { get; set; }
        public long ContentLogId { get; set; }
        public int OrganizationMasterId { get; set; }
        public string ContentType { get; set; }
        public string ComplianceTag { get; set; }
        public string ComplianceTagId { get; set; }
        public string ComplainceAssetId { get; set; }
        public System.DateTime EventColumnValue { get; set; }
        public bool IsProcessed { get; set; }
        public string ProcessStatus { get; set; }
        public string ProcessDescription { get; set; }
        public string LibraryName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DocId { get; set; }
    }
}
