//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colligo.O365Product.RM.Admin.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ColligoO365RMOEntities : DbContext
    {
        public ColligoO365RMOEntities()
            : base("name=ColligoO365RMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ErrorMessage> ErrorMessages { get; set; }
        public virtual DbSet<VwProductDetail> VwProductDetails { get; set; }
        public virtual DbSet<ContentLog> ContentLogs { get; set; }
        public virtual DbSet<EventSetting> EventSettings { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductLicense> ProductLicenses { get; set; }
        public virtual DbSet<ProductUser> ProductUsers { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<VwOrganization> VwOrganizations { get; set; }
        public virtual DbSet<VwOrganizationUserLicense> VwOrganizationUserLicenses { get; set; }
        public virtual DbSet<ADGAgent> ADGAgents { get; set; }
        public virtual DbSet<VwEventSetting> VwEventSettings { get; set; }
        public virtual DbSet<VwADGAgent> VwADGAgents { get; set; }
        public virtual DbSet<VwEventSettingUserSetup> VwEventSettingUserSetups { get; set; }
        public virtual DbSet<OrganizationUser> OrganizationUsers { get; set; }
        public virtual DbSet<VwOrganizationUser> VwOrganizationUsers { get; set; }
        public virtual DbSet<AgentExecutionTime> AgentExecutionTimes { get; set; }
    
        public virtual ObjectResult<DashboardResult> UspReportADGAgent(string organizationUrl, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string status)
        {
            var organizationUrlParameter = organizationUrl != null ?
                new ObjectParameter("OrganizationUrl", organizationUrl) :
                new ObjectParameter("OrganizationUrl", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardResult>("UspReportADGAgent", organizationUrlParameter, startDateParameter, endDateParameter, statusParameter);
        }
    
        public virtual ObjectResult<DashboardContentLog> UspReportGetContentLog(string organizationUrl, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> countError, Nullable<int> pageNbr, Nullable<int> pageSize)
        {
            var organizationUrlParameter = organizationUrl != null ?
                new ObjectParameter("OrganizationUrl", organizationUrl) :
                new ObjectParameter("OrganizationUrl", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var countErrorParameter = countError.HasValue ?
                new ObjectParameter("CountError", countError) :
                new ObjectParameter("CountError", typeof(bool));
    
            var pageNbrParameter = pageNbr.HasValue ?
                new ObjectParameter("PageNbr", pageNbr) :
                new ObjectParameter("PageNbr", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardContentLog>("UspReportGetContentLog", organizationUrlParameter, startDateParameter, endDateParameter, countErrorParameter, pageNbrParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<DashboardChartData> UspReportChartData(string organizationUrl, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var organizationUrlParameter = organizationUrl != null ?
                new ObjectParameter("OrganizationUrl", organizationUrl) :
                new ObjectParameter("OrganizationUrl", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DashboardChartData>("UspReportChartData", organizationUrlParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<ContentAuditSummary> UspReportContentAuditSummary(string organizationUrl, string searchTerm, Nullable<int> pageNbr, Nullable<int> pageSize)
        {
            var organizationUrlParameter = organizationUrl != null ?
                new ObjectParameter("OrganizationUrl", organizationUrl) :
                new ObjectParameter("OrganizationUrl", typeof(string));
    
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            var pageNbrParameter = pageNbr.HasValue ?
                new ObjectParameter("PageNbr", pageNbr) :
                new ObjectParameter("PageNbr", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ContentAuditSummary>("UspReportContentAuditSummary", organizationUrlParameter, searchTermParameter, pageNbrParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<EventSettingCount> UspEventSettingGetMappingCount(string organizationUrl)
        {
            var organizationUrlParameter = organizationUrl != null ?
                new ObjectParameter("OrganizationUrl", organizationUrl) :
                new ObjectParameter("OrganizationUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EventSettingCount>("UspEventSettingGetMappingCount", organizationUrlParameter);
        }
    }
}
