//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colligo.O365Product.RM.Admin.Data
{
    using System;
    
    public partial class ContentAuditSummary
    {
        public int Id { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public long ContentLogId { get; set; }
        public string ContentType { get; set; }
        public string DocId { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> EventColumnValue { get; set; }
        public string ComplianceTag { get; set; }
        public string ComplianceTagId { get; set; }
        public string ComplainceAssetId { get; set; }
        public string DocUrl { get; set; }
        public string DocumentName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<System.DateTime> EventCreatedDate { get; set; }
        public string ProcessDescription { get; set; }
    }
}
