//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colligo.O365Product.RM.Admin.Data
{
    using System;
    
    public partial class DashboardResult
    {
        public int ResultId { get; set; }
        public long ItemProcessedToday { get; set; }
        public long ItemProcessedToDate { get; set; }
        public long ItemErrorsToDate { get; set; }
        public long EventCreatedToday { get; set; }
        public long EventUpdatedToday { get; set; }
        public long EventCreatedToDate { get; set; }
        public long TotalActiveContentType { get; set; }
    }
}
