//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colligo.O365Product.RM.Admin.Data
{
    using System;
    
    public partial class DashboardChartData
    {
        public int OrganizationMasterId { get; set; }
        public Nullable<int> ResultSeries { get; set; }
        public int ItemProcessed { get; set; }
        public int ItemFailed { get; set; }
        public int EventCreated { get; set; }
        public string ReportTimeline { get; set; }
    }
}
