//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colligo.O365Product.RM.Admin.Data
{
    using System;
    
    public partial class EventSettingCount
    {
        public int MappedCount { get; set; }
        public string OrganizationRootUrl { get; set; }
        public string ContentSiteUrl { get; set; }
    }
}
