//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colligo.O365Product.RM.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwOrganizationUserLicense
    {
        public int OrganizationMasterId { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationId { get; set; }
        public Nullable<int> SystemUserId { get; set; }
        public string EmailAddress { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsOrganizationActive { get; set; }
        public Nullable<bool> IsUserActive { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsProductActive { get; set; }
        public Nullable<int> LicenseCount { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> IsProductUserActive { get; set; }
        public Nullable<int> LicenseUsed { get; set; }
    }
}
